### ISSUE TITLE
Redirect with https

### ISSUE THREAD

**Issue by EricOVGU** [tofi86/redmine_maintenance_mode#10]
Hello!
I use this plugin with redmine and https. When i activate the maintenance mode there is the message "...Der Wartungsmodus kann auf _dieser Seite_ beendet werden." on top. When I use the link I get a redirect without https => Not found error. Could this be an error caused by the plugin or maybe a configuration error by myself?

Thanks for Help!
Eric

**Comment by tofi86** [comment]
Hi, the protocol (http or https) is taken from the redmine settings. SO if you're using Redmine with HTTPS/SSL you need to set the Redmine configuration to use `Protocol: https` on admin->settings page.

**Comment by tofi86** [comment]
Can you verify that you set the protocol to https in your redmine settings? Is this still an issue?

**Comment by tofi86** [comment]
Closing this because no response.

Feel free to reopen if you think something is still wrong.
