### ISSUE TITLE
I18n::Missing Translation Data (translation missing: en.date.formats.default):

### ISSUE THREAD

**Issue by fjudith** [tofi86/redmine_maintenance_mode#12]
Hello,
Thanks a lot for your useful plugin.

I' getting the following error message once activated the maintenance mode.

**Redmine version 3.4.4**
```
Started GET "/login?back_url=https%3A%2F%2Fredmine.example.com%2F" for 123.123.123.123 at 2018-03-07 20:51:13 +0000
Processing by AccountController#login as HTML
  Parameters: {"back_url"=>"https://redmine.example.com/"}
  Current user: anonymous
Completed 500 Internal Server Error in 4ms (ActiveRecord: 0.8ms)

I18n::MissingTranslationData (translation missing: en.date.formats.default):
  lib/redmine/i18n.rb:71:in `format_date'
  lib/redmine/i18n.rb:82:in `format_time'
  plugins/redmine_maintenance_mode/lib/maintenance_mode_functions.rb:20:in `get_maintenance_plugin_settings'
  plugins/redmine_maintenance_mode/lib/maintenance_mode.rb:12:in `show_maintenance_mode_page'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

**Comment by tofi86** [comment]
Does this happen with the plain version of this plugin or with your fork?

I see that you changed the translation files and added this:
https://github.com/fjudith/redmine_maintenance_mode/commit/cf04b6c6c2c99ac64a6df8149bcf4a320a4476fd

Does this fix the issue?

Normally the `format_date` and `format_time` functions from redmine core use the default format date/time format defined in the redmine core language file in YAML key `en.date.formats.default`.

Can you make sure the default english language file `/config/locales/en.yml` exists in your redmine core?

**Comment by tofi86** [comment]
I am running a production version of Redmine 3.4.4 with the current plugin version and haven't encountered that problem yet, so I'm eager to learn what leads to this error.

**Comment by tofi86** [comment]
Also: would you mind sharing your french translation with the community and send it over as a PullRequest? Thanks! 🎉

**Comment by fjudith** [comment]
Hello @tofi86 
Thank you for your feedback
Surprisingly, The error message only appears with Firefox where english is enforce.
I have not been able to reproduce the issue using Edge, Internet Explorer and Chrome...

I will perform further investigations next week.

Notice that my Redmine instance is running  Abacus Office.

PR Has been submitted

**Comment by tofi86** [comment]
Hi Florian,

thanks for the update and the PR.

* Can you confirm that the file `config/locales/en.yml` exists in your redmine root directory?
  * Can you confirm that the specified key `en.date.formats.default` exists in this file?
* Could you ping the Abacus Office support, point them to this discussion and ask whether their theme alters language files or adds or overrides language configuration?
  * you can also try to disable the theme and run plain redmine with my plugin and test if it still happens...

**Comment by fjudith** [comment]
Hello @tofi86 ,

I'm closing this issue as i was'nt able to reproduce this issue since i upgraded my Firefox Beta browser.
I confirm that everything was fine regarding `config/locales/en.yml`.
I'm going to submit another PR for the french translation without the date format enforcement.
