### ISSUE TITLE
Redmine 4.x Compatibility

### ISSUE THREAD

**Issue by TitanFoxX** [tofi86/redmine_maintenance_mode#14]
Dear Tobias,

we've recently upgraded to Redmine 4.x due to the ability to use updated versions of Ruby, Rails and their gems. Unfortunately, your plugin does not (yet) support this Redmine version.

Are there any plans to apply this compatibility ? Honestly I think that this maintenance mode should be a default function by Redmine ;-)

Sincerely,
Ruud

**Comment by tofi86** [comment]
Hi Ruud,

thanks! Yes I definately planned to update the plugin for Redmine 4.

Time is limited at the moment but I'll have a look in the next couple of weeks.
Stay tuned.

Best,
Tobias

**Comment by tofi86** [comment]
Hi Ruud,

I added support for Redmine 4 / Rails 5 and released version 2.2.0
