### ISSUE TITLE
Formatting of content required for displaying message

### ISSUE THREAD

**Issue by lajish** [tofi86/redmine_maintenance_mode#7]
Hi Tobias,

Its been a long time to have a discussion with you. Hope you doing well.

Yesterday I had a thought that the maintenance message which we generally set to display to non admin user should have some sort of formatting. Such as bold/ italics/ increment/decrements of font size/ hyperlinks should behave as intended. Formatting which redmine provides while putting description against a tracker

I think, it would be better to incorporate these features in upcoming version.

Regards,
Lajish Lakshmanan

**Comment by tofi86** [comment]
textile or markdown formatting will be supported in the next version. added in 3091f5e on the `deface-views` branch.

you're welcome to test the changes by checking out the new `deface-views` branch.
**But attention!** You will first have to install the [Redmine Base Deface](https://github.com/jbbarth/redmine_base_deface) plugin! follow their installation notices, then update this plugin and then run `rake redmine:plugins:migrate RAILS_ENV=production`

**Comment by tofi86** [comment]
see [upgrade instructions](https://github.com/tofi86/redmine_maintenance_mode/tree/deface-views#upgrade-from-plugin-version-1x) for details

**Comment by tofi86** [comment]
the fix is merged and available in plugin 2.0.0

**Comment by lajish** [comment]
Hi there,

Thanks for adding the requested feature to plugin. I will surely test it and return back to you if i found any glitch in it.

Regards,
Lajish Lakshmanan
